# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Freiheit für Katharina
    url: '#about'
    weight: 10
  - name: Katharina's Brief
    url: '#gallery'
    weight: 20
  - name: Neuigkeiten
    url: '#posts'
    weight: 20
  - name: Posts
    url: '#posts'
    weight: 20
  - name: Fotos von Katharina
    url: '#gallery2'
    weight: 55    
  - name: Contact
    url: '#contact'
    weight: 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
